# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/

# Setup
title:               Touré A.Karim
tagline:             '- Personal Github Pages'
description:         'This is a personal project page that lists most important open source and personal projects made by <a href="https://github.com/trabdlkarim" target="_blank">@trabdlkarim</a>.'
url:                 https://projects.trabdlkarim.com
baseurl:             ''
paginate:            10
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Touré A.Karim
  url:               https://www.trabdlkarim.com
  email:             contact@trabdlkarim.com

# Custom vars
version:             1.0.0
