# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/

# Setup
title:               TOURE A. KARIM
tagline:             'A Personal Software Dev Lab'
description:         'This is a simple hub for some of <a href="https://github.com/trabdlkarim" target="_blank">@trabdlkarim</a> most important personal software development projects.'
url:                 https://devlabs.trabdlkarim.com
baseurl:             /
paginate:            5
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Touré A.Karim
  url:               www.trabdlkarim.com
  email:             contact@trabdlkarim.com

# Custom vars
version:             1.0.0
