# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/

# Setup
title:               TOURE A. KARIM
tagline:             'Personal Dev Labs'
description:         'This is a simple hub for some of <a href="https://github.com/trabdlkarim" target="_blank">@trabdlkarim's</a> most important open source and personal  software development projects.'
url:                 https://trabdlkarim.github.io
baseurl:             /
paginate:            5
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Touré A.Karim
  url:               www.trabdlkarim.com
  email:             contact@trabdlkarim.com

# Custom vars
version:             1.0.0
